sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
        - git checkout ${TRAVIS_BRANCH}
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t $DOCKER_USERNAME/tenncor-test:travis-${TRAVIS_COMMIT} .
        - docker images
        - docker push $DOCKER_USERNAME/tenncor-test:travis-${TRAVIS_COMMIT}
    - stage: fast test
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN}
          --rm $DOCKER_USERNAME/tenncor-test:travis-${TRAVIS_COMMIT} fast
    - stage: slow test
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN}
          --rm $DOCKER_USERNAME/tenncor-test:travis-${TRAVIS_COMMIT} slow

notifications:
  email: false

branches:
  except:
  - legacy

# safelist
branches:
  only:
  - master
  - /experimental(-.*)?/
  - stable
