language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov
  - sudo apt-get install -y lcov
  - wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel_0.9.0-linux-x86_64.deb
  - sha256sum -c setup/bazel_0.9.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.9.0-linux-x86_64.deb
  - bazel version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters
  - export GTEST_REPEAT=25
  - export GTEST_BREAK_ON_FAILURE=1
  - export GTEST_SHUFFLE=1

script:
  - cd ${TRAVIS_BUILD_DIR}
  - bazel test --run_under=valgrind --test_output=all//...
  - bazel test --collect_code_coverage --test_output=all //...
  - cat fuzz.out

after_success:
  # coverage log
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '**/gtest*' '**/tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug < see coverage here
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  except:
  - legacy

# safelist
branches:
  only:
  - master
  - stable
  - experimental
