sudo: required

services:
  - docker

jobs:
  include:
    - stage: build test docker image
      script:
        - git checkout ${TRAVIS_BRANCH}
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=travis-${TRAVIS_COMMIT} build_test_image
        - docker images
        - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=travis-${TRAVIS_COMMIT} push_test_image
    - stage: test fast
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN} --network=host
          --rm ${DOCKER_USERNAME}/tenncor-test:travis-${TRAVIS_COMMIT} fast
    - stage: test eteq
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN} --network=host
          --rm ${DOCKER_USERNAME}/tenncor-test:travis-${TRAVIS_COMMIT} eteq
    - stage: test layr
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN} --network=host
          --rm ${DOCKER_USERNAME}/tenncor-test:travis-${TRAVIS_COMMIT} layr
    - stage: test distrib
      script:
        - make test_consul_up
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN} --network=host
          --rm ${DOCKER_USERNAME}/tenncor-test:travis-${TRAVIS_COMMIT} distrib
        - make test_consul_down
    # disable making docker due to long build times
    # - stage: build docker image with C++ and python library
    #   script:
    #     - git checkout ${TRAVIS_BRANCH}
    #     - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    #     - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=${TRAVIS_COMMIT} build_lib_image
    #     - docker images
    #     - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=${TRAVIS_COMMIT} push_lib_image

notifications:
  email: false

branches:
  except:
  - legacy

# safelist
branches:
  only:
  - master
  - /experimental(-.*)?/
  - stable
