FROM mkaichen/bazel_cpp:081e0e24563758804fbb7d8b421db12a4674cb60

ENV APP_DIR /usr/src/tenncor

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

COPY . $APP_DIR
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "./scripts/tests.sh", "." ]
