licenses(["notice"])

#######################################
#             TEST FILES              #
#######################################

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "//tests/graphmgr:srcs",
        "//tests/py_save:srcs",
        "//tests/regress:srcs",
        "//tests/unit:srcs",
        "//tests/utils:srcs",
    ],
    visibility = [ "//visibility:public" ],
)
