// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbg/profile/profile.proto

#include "dbg/profile/profile.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_internal_2fonnx_2fonnx_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_ModelProto_internal_2fonnx_2fonnx_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_dbg_2fprofile_2fprofile_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto;
namespace tenncor_profile {
class CreateProfileRequest_RuntimeEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CreateProfileRequest_RuntimeEntry_DoNotUse> _instance;
} _CreateProfileRequest_RuntimeEntry_DoNotUse_default_instance_;
class CreateProfileRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CreateProfileRequest> _instance;
} _CreateProfileRequest_default_instance_;
class CreateProfileResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CreateProfileResponse> _instance;
} _CreateProfileResponse_default_instance_;
}  // namespace tenncor_profile
static void InitDefaultsscc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tenncor_profile::_CreateProfileRequest_default_instance_;
    new (ptr) ::tenncor_profile::CreateProfileRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tenncor_profile::CreateProfileRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto}, {
      &scc_info_ModelProto_internal_2fonnx_2fonnx_2eproto.base,
      &scc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto.base,}};

static void InitDefaultsscc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tenncor_profile::_CreateProfileRequest_RuntimeEntry_DoNotUse_default_instance_;
    new (ptr) ::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse();
  }
  ::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto}, {}};

static void InitDefaultsscc_info_CreateProfileResponse_dbg_2fprofile_2fprofile_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tenncor_profile::_CreateProfileResponse_default_instance_;
    new (ptr) ::tenncor_profile::CreateProfileResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tenncor_profile::CreateProfileResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CreateProfileResponse_dbg_2fprofile_2fprofile_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CreateProfileResponse_dbg_2fprofile_2fprofile_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_dbg_2fprofile_2fprofile_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_dbg_2fprofile_2fprofile_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_dbg_2fprofile_2fprofile_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_dbg_2fprofile_2fprofile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest, model_),
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileRequest, runtime_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tenncor_profile::CreateProfileResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse)},
  { 9, -1, sizeof(::tenncor_profile::CreateProfileRequest)},
  { 16, -1, sizeof(::tenncor_profile::CreateProfileResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tenncor_profile::_CreateProfileRequest_RuntimeEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tenncor_profile::_CreateProfileRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tenncor_profile::_CreateProfileResponse_default_instance_),
};

const char descriptor_table_protodef_dbg_2fprofile_2fprofile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031dbg/profile/profile.proto\022\017tenncor_pro"
  "file\032\030internal/onnx/onnx.proto\"\254\001\n\024Creat"
  "eProfileRequest\022\037\n\005model\030\001 \001(\0132\020.onnx.Mo"
  "delProto\022C\n\007runtime\030\002 \003(\01322.tenncor_prof"
  "ile.CreateProfileRequest.RuntimeEntry\032.\n"
  "\014RuntimeEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
  "\003:\0028\001\"\027\n\025CreateProfileResponse2w\n\025Tennco"
  "rProfileService\022^\n\rCreateProfile\022%.tennc"
  "or_profile.CreateProfileRequest\032&.tennco"
  "r_profile.CreateProfileResponseb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_dbg_2fprofile_2fprofile_2eproto_deps[1] = {
  &::descriptor_table_internal_2fonnx_2fonnx_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_dbg_2fprofile_2fprofile_2eproto_sccs[3] = {
  &scc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto.base,
  &scc_info_CreateProfileRequest_RuntimeEntry_DoNotUse_dbg_2fprofile_2fprofile_2eproto.base,
  &scc_info_CreateProfileResponse_dbg_2fprofile_2fprofile_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_dbg_2fprofile_2fprofile_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dbg_2fprofile_2fprofile_2eproto = {
  false, false, descriptor_table_protodef_dbg_2fprofile_2fprofile_2eproto, "dbg/profile/profile.proto", 399,
  &descriptor_table_dbg_2fprofile_2fprofile_2eproto_once, descriptor_table_dbg_2fprofile_2fprofile_2eproto_sccs, descriptor_table_dbg_2fprofile_2fprofile_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_dbg_2fprofile_2fprofile_2eproto::offsets,
  file_level_metadata_dbg_2fprofile_2fprofile_2eproto, 3, file_level_enum_descriptors_dbg_2fprofile_2fprofile_2eproto, file_level_service_descriptors_dbg_2fprofile_2fprofile_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_dbg_2fprofile_2fprofile_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_dbg_2fprofile_2fprofile_2eproto)), true);
namespace tenncor_profile {

// ===================================================================

CreateProfileRequest_RuntimeEntry_DoNotUse::CreateProfileRequest_RuntimeEntry_DoNotUse() {}
CreateProfileRequest_RuntimeEntry_DoNotUse::CreateProfileRequest_RuntimeEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void CreateProfileRequest_RuntimeEntry_DoNotUse::MergeFrom(const CreateProfileRequest_RuntimeEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata CreateProfileRequest_RuntimeEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void CreateProfileRequest_RuntimeEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void CreateProfileRequest::InitAsDefaultInstance() {
  ::tenncor_profile::_CreateProfileRequest_default_instance_._instance.get_mutable()->model_ = const_cast< ::onnx::ModelProto*>(
      ::onnx::ModelProto::internal_default_instance());
}
class CreateProfileRequest::_Internal {
 public:
  static const ::onnx::ModelProto& model(const CreateProfileRequest* msg);
};

const ::onnx::ModelProto&
CreateProfileRequest::_Internal::model(const CreateProfileRequest* msg) {
  return *msg->model_;
}
void CreateProfileRequest::clear_model() {
  if (GetArena() == nullptr && model_ != nullptr) {
    delete model_;
  }
  model_ = nullptr;
}
CreateProfileRequest::CreateProfileRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  runtime_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tenncor_profile.CreateProfileRequest)
}
CreateProfileRequest::CreateProfileRequest(const CreateProfileRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  runtime_.MergeFrom(from.runtime_);
  if (from._internal_has_model()) {
    model_ = new ::onnx::ModelProto(*from.model_);
  } else {
    model_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tenncor_profile.CreateProfileRequest)
}

void CreateProfileRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto.base);
  model_ = nullptr;
}

CreateProfileRequest::~CreateProfileRequest() {
  // @@protoc_insertion_point(destructor:tenncor_profile.CreateProfileRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateProfileRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete model_;
}

void CreateProfileRequest::ArenaDtor(void* object) {
  CreateProfileRequest* _this = reinterpret_cast< CreateProfileRequest* >(object);
  (void)_this;
}
void CreateProfileRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateProfileRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CreateProfileRequest& CreateProfileRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CreateProfileRequest_dbg_2fprofile_2fprofile_2eproto.base);
  return *internal_default_instance();
}


void CreateProfileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:tenncor_profile.CreateProfileRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  runtime_.Clear();
  if (GetArena() == nullptr && model_ != nullptr) {
    delete model_;
  }
  model_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateProfileRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .onnx.ModelProto model = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_model(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, int64> runtime = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&runtime_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateProfileRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tenncor_profile.CreateProfileRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .onnx.ModelProto model = 1;
  if (this->has_model()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::model(this), target, stream);
  }

  // map<string, int64> runtime = 2;
  if (!this->_internal_runtime().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "tenncor_profile.CreateProfileRequest.RuntimeEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_runtime().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_runtime().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >::const_iterator
          it = this->_internal_runtime().begin();
          it != this->_internal_runtime().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = CreateProfileRequest_RuntimeEntry_DoNotUse::Funcs::InternalSerialize(2, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >::const_iterator
          it = this->_internal_runtime().begin();
          it != this->_internal_runtime().end(); ++it) {
        target = CreateProfileRequest_RuntimeEntry_DoNotUse::Funcs::InternalSerialize(2, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tenncor_profile.CreateProfileRequest)
  return target;
}

size_t CreateProfileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tenncor_profile.CreateProfileRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, int64> runtime = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_runtime_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >::const_iterator
      it = this->_internal_runtime().begin();
      it != this->_internal_runtime().end(); ++it) {
    total_size += CreateProfileRequest_RuntimeEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .onnx.ModelProto model = 1;
  if (this->has_model()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *model_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateProfileRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tenncor_profile.CreateProfileRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateProfileRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateProfileRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tenncor_profile.CreateProfileRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tenncor_profile.CreateProfileRequest)
    MergeFrom(*source);
  }
}

void CreateProfileRequest::MergeFrom(const CreateProfileRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tenncor_profile.CreateProfileRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  runtime_.MergeFrom(from.runtime_);
  if (from.has_model()) {
    _internal_mutable_model()->::onnx::ModelProto::MergeFrom(from._internal_model());
  }
}

void CreateProfileRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tenncor_profile.CreateProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateProfileRequest::CopyFrom(const CreateProfileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tenncor_profile.CreateProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateProfileRequest::IsInitialized() const {
  return true;
}

void CreateProfileRequest::InternalSwap(CreateProfileRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  runtime_.Swap(&other->runtime_);
  swap(model_, other->model_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateProfileRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CreateProfileResponse::InitAsDefaultInstance() {
}
class CreateProfileResponse::_Internal {
 public:
};

CreateProfileResponse::CreateProfileResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tenncor_profile.CreateProfileResponse)
}
CreateProfileResponse::CreateProfileResponse(const CreateProfileResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tenncor_profile.CreateProfileResponse)
}

void CreateProfileResponse::SharedCtor() {
}

CreateProfileResponse::~CreateProfileResponse() {
  // @@protoc_insertion_point(destructor:tenncor_profile.CreateProfileResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateProfileResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CreateProfileResponse::ArenaDtor(void* object) {
  CreateProfileResponse* _this = reinterpret_cast< CreateProfileResponse* >(object);
  (void)_this;
}
void CreateProfileResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateProfileResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CreateProfileResponse& CreateProfileResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CreateProfileResponse_dbg_2fprofile_2fprofile_2eproto.base);
  return *internal_default_instance();
}


void CreateProfileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tenncor_profile.CreateProfileResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateProfileResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateProfileResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tenncor_profile.CreateProfileResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tenncor_profile.CreateProfileResponse)
  return target;
}

size_t CreateProfileResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tenncor_profile.CreateProfileResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateProfileResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tenncor_profile.CreateProfileResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateProfileResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateProfileResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tenncor_profile.CreateProfileResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tenncor_profile.CreateProfileResponse)
    MergeFrom(*source);
  }
}

void CreateProfileResponse::MergeFrom(const CreateProfileResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tenncor_profile.CreateProfileResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void CreateProfileResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tenncor_profile.CreateProfileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateProfileResponse::CopyFrom(const CreateProfileResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tenncor_profile.CreateProfileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateProfileResponse::IsInitialized() const {
  return true;
}

void CreateProfileResponse::InternalSwap(CreateProfileResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateProfileResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tenncor_profile
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse* Arena::CreateMaybeMessage< ::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tenncor_profile::CreateProfileRequest_RuntimeEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::tenncor_profile::CreateProfileRequest* Arena::CreateMaybeMessage< ::tenncor_profile::CreateProfileRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tenncor_profile::CreateProfileRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::tenncor_profile::CreateProfileResponse* Arena::CreateMaybeMessage< ::tenncor_profile::CreateProfileResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tenncor_profile::CreateProfileResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
